spring.application.name=API-Gateway
# Général

server.port=8080

# --- ROUTE USER (merged Student and Supervisor) ---
# Pour Student : On ne coupe rien (StripPrefix=0)
spring.cloud.gateway.routes[0].id=student-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/students/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

# --- ROUTE DOCUMENT (NestJS) ---
# Pour Student : On ne coupe rien (StripPrefix=0)



spring.cloud.gateway.routes[1].id=supervisor-route
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/supervisor/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0
logging.level.org.springframework.cloud.gateway=TRACE
# On garde 2 car NestJS attend la racine "/"
# Code Nest : @Controller('documents')
pring.cloud.gateway.routes[2].id=document-route
spring.cloud.gateway.routes[2].uri=lb://DOCUMENT-SERVICE
# On ajoute une étoile supplémentaire pour bien capturer tout le chemin
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/documents/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=company-route
spring.cloud.gateway.routes[3].uri=lb://COMPANY
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/companies/**
# On laisse 0 pour ne pas couper le /api dont le code Java a besoin
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=0
# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/