spring.application.name=eureka-discovery-service
server.port=8761

# 1. Empêche le serveur de s'enregistrer lui-même comme un client
eureka.client.register-with-eureka=false

# 2. Empêche le serveur d'aller chercher la liste des services (puisqu'il est la source)
eureka.client.fetch-registry=false

# Désactivation du mode auto-préservation (utile en développement pour voir les changements vite)
eureka.server.enable-self-preservation=false