spring.application.name=Supervisor
server.port=8086

# Configuration H2
spring.datasource.url=jdbc:h2:mem:supervisordb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
