# Nom de l'application et port
spring.application.name=Config-Service
server.port=8888

# --- CONFIGURATION NATIVE (Fichiers locaux) ---
# Active le mode local pour lire les fichiers dans classpath:/configurations
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations

# --- DÉSACTIVATION EUREKA ---
# Désactive complètement le client Eureka pour ce service
eureka.client.enabled=false

# Optionnel : force la désactivation de l'enregistrement et de la récupération
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false